name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build-and-push:
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    runs-on: ${{ contains(matrix.platform, 'arm64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: latest_release
        run: |
          echo "ANKI_VERSION=$(curl -s https://api.github.com/repos/ankitects/anki/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Checkout anki repository
        uses: actions/checkout@v4
        with:
          repository: ankitects/anki
          ref: main
          path: anki

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./anki/docs/syncserver
          push: true
          build-args: |
            ANKI_VERSION=${{ env.ANKI_VERSION }}
          tags: ghcr.io/mt190502/docker-anki-sync-server:${{ env.ANKI_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}

      - name: Create and push tag and release
        if: matrix.platform == 'linux/amd64'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Creating tag and release for version ${{ env.ANKI_VERSION }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.ANKI_VERSION }} || true
          git push origin ${{ env.ANKI_VERSION }} || true
          gh release create ${{ env.ANKI_VERSION }} --generate-notes || true
